### ISSUE TITLE
Order schedule process date changes do not bump subsequent processes

### ISSUE THREAD

**Issue by bhaugen** [valueflows/valuenetwork#1]
See https://valnet.lurker.dev/accounting/order-schedule/1/

Changed date on Translate to later, did not bump Copyedit etc.

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/valuenetwork/-/issues/1.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
