### ISSUE TITLE
"Too Many Redirects" for non-staff users

### ISSUE THREAD

**Issue by JamesVorder** [valueflows/valuenetwork#2]
> James. what I did to make it work for Stephanie is made her a staff
> user. That fixed the "too many redirects" problem.
> 
> But
> 1) I am not sure why, so there's still an underlying problem.
> 2) That only works if we want to make everybody a staff user.
> 
> So it's a good clue, and maybe a good temporary solution, but maybe
> not a good permanent solution.

## Steps To Reproduce

1. Create a non-staff account
1. Log in with that account
1. Navigate to the "Organization" tab

Expected behavior: The organization page is shown
Actual behavior: Error! "The page isn't redirecting properly"

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/valuenetwork/-/issues/2.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
